spring.application.name=hotel-booking
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/HotelDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}

spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP - SSL cho Neon.tech (production)
spring.datasource.hikari.data-source-properties.sslmode=${SSL_MODE:disable}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:dattruong02112004@gmail.com}
spring.mail.password=${MAIL_PASSWORD:nakc qivm jkke spnq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:do8uakd0l}
cloudinary.api-key=${CLOUDINARY_API_KEY:124513174452738}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:oTRHfiIPZEtBz7jW1hswkIAcwVw}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

server.servlet.context-path=/api

google.client_id=${GOOGLE_CLIENT_ID:your-client-id}
google.client_secret=${GOOGLE_CLIENT_SECRET:your-client-secret}

vnpay.tmnCode=${VNPAY_TMN_CODE:BFU9A8LN}
vnpay.hashSecret=${VNPAY_HASH_SECRET:JRLSIA8E1QNH30SCCLDBRHAYN1OFH09V}
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=${VNPAY_RETURN_URL:https://localhost:8080/api/customer/booking/payment/vnpay-return}

vnpay.version=2.1.0
vnpay.command=pay
vnpay.currCode=VND
vnpay.locale=vn
